#!/usr/bin/env python
from __future__ import print_function, division

import json
import argparse
import numpy as np
import matplotlib.pyplot as plt


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('loss_log_jsons', nargs='+')
    parser.add_argument('-s', '--show-plot', action='store_true')
    args = parser.parse_args()
    plt.figure(figsize=(12, 10))
    for loss_log_json in sorted(args.loss_log_jsons):
        with open(loss_log_json, mode='r') as f:
            loss_log = json.load(f)

        line = plt.plot([epoch['training_loss'] for epoch in loss_log],
                        '-', linewidth=0.5)
        plt.plot([epoch['validation loss'] for epoch in loss_log],
                 '-', label=loss_log_json, color=line[0].get_color(),
                 linewidth=2.0)

    plt.grid()
    plt.legend()
    plt.savefig('validation_plot.png')
    if args.show_plot:
        plt.show()

if __name__ == '__main__':
    main()
